# Generated by Django 5.2.17 on 2026-08-21 15:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('usage_scope', models.CharField(max_length=180)),
                ('summary', models.CharField(max_length=255)),
                ('terms_version', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('sku', models.CharField(max_length=40, unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('audio_format', models.CharField(choices=[('wav', 'WAV'), ('flac', 'FLAC'), ('aiff', 'AIFF')], max_length=8)),
                ('sample_rate_hz', models.PositiveIntegerField()),
                ('bit_depth', models.PositiveSmallIntegerField()),
                ('preview_file', models.FileField(blank=True, upload_to='previews/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProductLicenseOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='EUR', editable=False, max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_offers', to='catalog.licensetype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_offers', to='catalog.product')),
            ],
            options={
                'ordering': ['price', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('product', 'license_type'), name='uniq_product_license_offer'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='product_license_price_nonnegative')],
            },
        ),
    ]
