# Generated by Django 5.2.17 on 2026-08-28 11:14

import apps.catalog.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='master_file',
            field=models.FileField(blank=True, storage=apps.catalog.storage.PrivateMasterStorage(), upload_to='masters/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_file',
            field=models.FileField(blank=True, storage=apps.catalog.storage.PreviewStorage(), upload_to='previews/'),
        ),
    ]
